services:
  server:
    build:
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    healthcheck:
      test: curl --fail http://localhost:${SERVER_PORT}/v1/state || exit 1
      interval: 60s
      timeout: 10s
      retries: 2
      start_period: 10s
